export const actionsType = {
    CREATE_USER:'CREATE_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_TYPE: 'SET_USER_TYPE',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    SET_USERS: 'SET_USERS',

    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
    SET_GUEST_ITEMS_TO_USER: 'SET_GUEST_ITEMS_TO_USER',

    //Shop Action Types
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',

    CREATE_ORDER: 'CREATE_ORDER',
    REMOVE_ORDER: 'REMOVE_ORDER',
    EDIT_ORDER: 'EDIT_ORDER'
};